const SDK = 'https://www.gstatic.com/firebasejs/12.19.0/';
const ISSUE_TYPES = ['使用時間過長','不恰當資料（相片／影片）','觀看視頻過多（如 YouTube）','其他問題'];
const app = document.querySelector('#app');
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const email = s => String(s||'').trim().toLowerCase();
const today = () => new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Hong_Kong',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const stamp = () => new Intl.DateTimeFormat('zh-HK',{timeZone:'Asia/Hong_Kong',dateStyle:'medium',timeStyle:'short'}).format(new Date());
const toast = m => {let n=document.querySelector('#toast');n.textContent=m;n.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>n.style.display='none',3500)};
const uid = () => crypto.randomUUID();
const sample = (items,n) => {const a=[...items];for(let i=a.length-1;i>0;i--){const bytes=new Uint32Array(1);crypto.getRandomValues(bytes);const j=bytes[0]%(i+1);[a[i],a[j]]=[a[j],a[i]]}return a.slice(0,n)};
const parseRoster = raw => [...new Set(raw.split(/\r?\n/).map(s=>s.trim()).filter(Boolean))].map((name,i)=>({id:`s${i+1}`,name}));
let auth, db, F, A, user=null, admin=false, actions=[], unsub=null, progressUnsubs=[], screen='home', current=null, detail=null, progress=[], reportAssignments=[];
let drafts=[{id:uid(),label:'',teacherEmail:'',roster:''}];
let formDraft={title:'學生 iPad 特擊抽查',date:today(),grade:'',coordinatorName:'',coordinatorEmail:'',defaultCount:'5'};
function syncForm(){let f=document.querySelector('#createForm');if(f)for(let key of Object.keys(formDraft))formDraft[key]=f.elements[key]?.value??formDraft[key]}
let config;
try { config=(await import('./firebase-config.js')).firebaseConfig; } catch {}
if (!config?.apiKey || !config?.projectId) {
 app.innerHTML='<main class="shell"><div class="top"><div class="brand">藍循 · 學生 iPad 抽查</div></div><section class="card"><h1>系統尚未連接資料庫</h1><p>程式已備妥。管理員需按 README 建立 Firebase 專案，填入設定及部署權限規則，之後先可以登入及保存真正紀錄。</p><p class="notice">請勿喺未完成權限設定前輸入學生資料。</p></section></main>';
} else {
 const [{initializeApp},{getAuth,GoogleAuthProvider,signInWithPopup,signInWithRedirect,getRedirectResult,signOut,onAuthStateChanged},{getFirestore,collection,doc,getDoc,getDocs,setDoc,updateDoc,writeBatch,onSnapshot,query,where,serverTimestamp,runTransaction}] = await Promise.all([import(SDK+'firebase-app.js'),import(SDK+'firebase-auth.js'),import(SDK+'firebase-firestore.js')]);
 const firebase=initializeApp(config); auth=getAuth(firebase);db=getFirestore(firebase);
 F={collection,doc,getDoc,getDocs,setDoc,updateDoc,writeBatch,onSnapshot,query,where,serverTimestamp,runTransaction};A={GoogleAuthProvider,signInWithPopup,signInWithRedirect,signOut};
 getRedirectResult(auth).catch(e=>toast('登入未完成：'+e.message));
 onAuthStateChanged(auth, async u=>{if(unsub)unsub();progressUnsubs.forEach(fn=>fn());progressUnsubs=[]; user=u;actions=[];current=null;detail=null;admin=false;if(u){try {admin=(await getDoc(doc(db,'admins',u.uid))).exists();listenActions()}catch(e){toast('無法讀取權限：'+e.message)}}render()});
}
function shell(body){app.innerHTML=`<main class="shell"><header class="top"><div><div class="brand">藍循 · 學生 iPad 抽查</div><div class="sub">手機抽查紀錄系統</div></div>${user?`<button class="btn ghost sm no-print" data-act="logout">登出</button>`:''}</header>${user?`<nav class="tabs no-print"><button data-act="home" class="${screen==='home'?'sel':''}">行動</button>${admin?`<button data-act="new" class="${screen==='new'?'sel':''}">新增行動</button>`:''}<button data-act="history" class="${screen==='history'?'sel':''}">歷史紀錄</button></nav>`:''}${body}</main>`}
function render(){if(!config?.apiKey)return;if(!user){shell('<section class="card"><h1>教師登入</h1><p>請用學校指定 Google 帳戶登入；只有獲指派嘅老師可以開啟抽查紀錄。</p><button class="btn" data-act="login">使用 Google 登入</button></section>');return}
 if(screen==='new'&&admin)return renderNew();if(screen==='detail'&&current)return renderDetail();if(screen==='report'&&current)return renderReport();
 let list=actions.filter(a=>screen==='history'?a.status==='completed':a.status!=='completed');
 shell(`<div class="row between"><h1>${screen==='history'?'歷史紀錄':'抽查行動'}</h1><span class="pill">${admin?'管理員':'負責老師'}</span></div>${list.length?`<div class="list">${list.map(actionCard).join('')}</div>`:'<div class="card empty">暫時未有相關行動</div>'}`)
}
function actionCard(a){let p=a.progress||{}, total=(a.classes||[]).length,done=Object.values(p).filter(x=>x.done).length, percent=total?Math.round(done/total*100):0;return `<article class="card"><div class="row between"><div><div class="action-title">${esc(a.title)}</div><div class="small muted">${esc(a.date)} · ${esc(a.grade)} · ${total} 班 · 統籌：${esc(a.coordinatorName||a.coordinatorEmail)}</div></div><span class="pill ${a.status==='completed'?'done':''}">${a.status==='completed'?'已完成':'進行中'}</span></div><div class="progress"><i style="width:${percent}%"></i></div><div class="row between"><span class="small">${done}/${total} 班完成</span><button class="btn secondary sm" data-act="open" data-id="${esc(a.id)}">查看及處理</button></div></article>`}
function listenActions(){const col=collection(db,'actions');const q=admin?query(col):query(col,where('participantEmails','array-contains',email(user.email)));unsub=onSnapshot(q,s=>{progressUnsubs.forEach(fn=>fn());progressUnsubs=[];actions=s.docs.map(d=>({id:d.id,...d.data(),progress:{}})).sort((a,b)=>(b.date||'').localeCompare(a.date||'')||(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));actions.forEach(a=>{const off=onSnapshot(collection(db,'actions',a.id,'progress'),snap=>{a.progress=Object.fromEntries(snap.docs.map(d=>[d.id,d.data()]));render()},err=>toast('進度同步失敗：'+err.message));progressUnsubs.push(off)});render()},e=>{toast('無法同步行動：'+e.message);render()})}
function renderNew(){shell(`<h1>新增抽查行動</h1><form id="createForm" class="card"><div class="fieldrow"><label>行動名稱<input name="title" required value="${esc(formDraft.title)}"></label><label>日期<input name="date" type="date" required value="${esc(formDraft.date)}"></label><label>年級<input name="grade" required placeholder="例如：四年級" value="${esc(formDraft.grade)}"></label></div><div class="fieldrow"><label>統籌人姓名<input name="coordinatorName" required value="${esc(formDraft.coordinatorName)}"></label><label>統籌人 Google 電郵<input name="coordinatorEmail" type="email" required value="${esc(formDraft.coordinatorEmail||user.email)}"></label><label>每班預設抽查人數<input name="defaultCount" type="number" min="1" max="50" value="${esc(formDraft.defaultCount)}" required></label></div><div class="row between" style="margin-top:18px"><h2>班別與負責老師</h2><button type="button" class="btn secondary sm" data-act="addClass">＋ 加一班</button></div><p class="small muted">每班貼上完整學生名單，一行一人。可輸入「學號 姓名」或單獨姓名；學號會作名稱的一部分保留。建立後名單會成為該次行動的快照。</p><div id="classEditors">${drafts.map((d,i)=>`<div class="class-editor" data-draft="${esc(d.id)}"><div class="row between"><h3>第 ${i+1} 班</h3>${drafts.length>1?`<button class="btn danger sm" type="button" data-act="removeClass" data-id="${esc(d.id)}">移除</button>`:''}</div><div class="fieldrow"><label>班別<input data-field="label" required placeholder="例如 4A" value="${esc(d.label)}"></label><label>負責老師電郵<input data-field="teacherEmail" type="email" required placeholder="teacher@school.edu.hk" value="${esc(d.teacherEmail)}"></label></div><label>學生名單<textarea data-field="roster" required rows="5" placeholder="01 陳同學&#10;02 李同學">${esc(d.roster)}</textarea></label><div class="small muted">${parseRoster(d.roster).length} 人</div></div>`).join('')}</div><button class="btn" type="submit">建立行動</button></form>`)}
function syncDrafts(){document.querySelectorAll('[data-draft]').forEach(el=>{let d=drafts.find(x=>x.id===el.dataset.draft);if(d)el.querySelectorAll('[data-field]').forEach(f=>d[f.dataset.field]=f.value)})}
async function createAction(form){syncDrafts();const fd=new FormData(form),count=Number(fd.get('defaultCount'));if(!Number.isInteger(count)||count<1||count>50)throw Error('抽查人數必須介乎 1 至 50');let cls=drafts.map(d=>({...d,label:d.label.trim(),teacherEmail:email(d.teacherEmail),students:parseRoster(d.roster)}));if(cls.some(c=>!c.label||!c.teacherEmail||!c.students.length||count>c.students.length))throw Error('請填妥各班資料；抽查人數不能多於班內人數');if(new Set(cls.map(c=>c.label)).size!==cls.length)throw Error('班別不能重複');if(cls.length>30)throw Error('每次最多 30 班');let coord=email(fd.get('coordinatorEmail'));const ref=doc(collection(db,'actions')),participants=[...new Set([coord,...cls.map(c=>c.teacherEmail)])];const batch=writeBatch(db);const classes=cls.map((c,i)=>{let id='c'+(i+1);batch.set(doc(db,'actions',ref.id,'progress',id),{total:count,checked:0,done:false,teacherEmail:c.teacherEmail});batch.set(doc(db,'actions',ref.id,'assignments',id),{label:c.label,teacherEmail:c.teacherEmail,roster:c.students,sampleCount:count,selected:[],replacementLog:[],records:{},updatedAt:serverTimestamp()});return{id,label:c.label,teacherEmail:c.teacherEmail}});batch.set(ref,{title:String(fd.get('title')).trim(),date:String(fd.get('date')),grade:String(fd.get('grade')).trim(),coordinatorName:String(fd.get('coordinatorName')).trim(),coordinatorEmail:coord,participantEmails:participants,classes,status:'active',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await batch.commit();drafts=[{id:uid(),label:'',teacherEmail:'',roster:''}];formDraft={title:'學生 iPad 特擊抽查',date:today(),grade:'',coordinatorName:'',coordinatorEmail:'',defaultCount:'5'};screen='home';toast('行動已建立');render()}
const isLead=a=>admin||email(a.coordinatorEmail)===email(user?.email);
async function openAction(id){current=actions.find(a=>a.id===id);if(!current)return;screen='detail';await refreshDetail()}
async function refreshDetail(){if(!current)return;const cls=current.classes.filter(c=>isLead(current)||c.teacherEmail===email(user.email));let snaps=await Promise.all(cls.map(c=>getDoc(doc(db,'actions',current.id,'assignments',c.id))));detail=snaps.map((s,i)=>({meta:cls[i],...(s.exists()?s.data():{})}));render()}
function renderDetail(){const a=actions.find(x=>x.id===current.id)||current;current=a;let p=a.progress||{},done=Object.values(p).filter(x=>x.done).length,total=a.classes.length;let own=detail||[];shell(`<div class="row between"><div><h1>${esc(a.title)}</h1><div class="small muted">${esc(a.date)} · ${esc(a.grade)} · 統籌：${esc(a.coordinatorName)} (${esc(a.coordinatorEmail)})</div></div><span class="pill ${a.status==='completed'?'done':''}">${a.status==='completed'?'已完成':'進行中'}</span></div><section class="card"><div class="row between"><strong>全組進度 ${done}/${total} 班</strong><button class="btn ghost sm no-print" data-act="report">整體報告</button></div><div class="progress"><i style="width:${total?done/total*100:0}%"></i></div>${a.classes.map(c=>{let x=p[c.id]||{};return `<div class="assign"><span>${esc(c.label)} · ${esc(c.teacherEmail)}</span><span class="pill ${x.done?'done':x.checked?'warn':''}">${x.done?'已完成':`${x.checked||0}/${x.total||0}`}</span></div>`}).join('')}</section>${own.map(renderAssignment).join('')}${isLead(a)?`<div class="card no-print"><div class="row between"><div><strong>行動狀態</strong><div class="small muted">完成後仍可翻查及列印報告。</div></div><button class="btn ${a.status==='completed'?'secondary':'danger'} sm" data-act="toggleStatus">${a.status==='completed'?'重新開啟':'標示整體完成'}</button></div></div>`:''}`)}
function renderAssignment(c){let a=current,sel=c.selected||[],rec=c.records||{},n=c.sampleCount,done=sel.filter(id=>rec[id]?.result).length,canEdit=a.status==='active'&&c.teacherEmail===email(user.email), roster=Object.fromEntries((c.roster||[]).map(s=>[s.id,s]));return `<section class="card active"><div class="row between"><div><h2>${esc(c.label)} · ${esc(c.teacherEmail)}</h2><span class="small muted">已查 ${done}/${n} · 全班 ${c.roster?.length||0} 人</span></div><span class="pill ${done===n&&sel.length===n?'done':''}">${done===n&&sel.length===n?'本班完成':'處理中'}</span></div>${!sel.length?`<p class="small muted">按下抽樣後，由系統隨機揀選 ${n} 位學生。</p>${canEdit?`<button class="btn" data-act="draw" data-class="${esc(c.meta.id)}">隨機抽選 ${n} 人</button>`:''}`:sel.map((id,i)=>renderStudent(c,roster[id],i,canEdit)).join('')}${c.replacementLog?.length?`<details><summary class="small">缺席及重抽記錄 (${c.replacementLog.length})</summary><ul class="small">${c.replacementLog.map(x=>`<li>${esc(x.at)}：${esc(x.outName)} 缺席 → ${esc(x.inName)}</li>`).join('')}</ul></details>`:''}</section>`}
function renderStudent(c,s,i,edit){if(!s)return '';const r=c.records?.[s.id]||{},issues=r.issues||[],id=esc(s.id),cid=esc(c.meta.id);return `<div class="student" data-record-class="${cid}" data-student="${id}"><div class="student-head"><span class="student-name">${i+1}. ${esc(s.name)}</span><span class="pill ${r.result==='ok'?'done':r.result==='issue'?'warn':''}">${r.result==='ok'?'沒有問題':r.result==='issue'?'有問題':'待檢查'}</span></div>${edit?`<div class="choices"><label class="choice"><input type="radio" name="result-${cid}-${id}" value="ok" ${r.result==='ok'?'checked':''}>沒有問題</label><label class="choice"><input type="radio" name="result-${cid}-${id}" value="issue" ${r.result==='issue'?'checked':''}>有問題</label></div><div class="issues choices ${r.result==='issue'?'':'hidden'}">${ISSUE_TYPES.map((x,j)=>`<label class="choice"><input type="checkbox" value="${j}" ${issues.includes(x)?'checked':''}>${esc(x)}</label>`).join('')}</div><label>檢查備註<textarea data-part="remarks" rows="2" placeholder="可留空">${esc(r.remarks||'')}</textarea></label><label class="choice"><input type="checkbox" data-part="follow" ${r.followUp?'checked':''}>需要跟進</label><div class="follow-fields ${r.followUp?'':'hidden'} fieldrow"><label>跟進日期<input type="date" data-part="followDate" value="${esc(r.followDate||'')}"></label><label>跟進備註<textarea data-part="followNotes" rows="2">${esc(r.followNotes||'')}</textarea></label></div><div class="row between" style="margin-top:9px"><button class="btn ghost sm" data-act="replace" data-class="${cid}" data-student="${id}">學生缺席 · 重抽</button><button class="btn sm" data-act="save" data-class="${cid}" data-student="${id}">儲存結果</button></div>`:`<div class="small muted" style="margin-top:6px">${r.result==='issue'?esc(issues.join('、')):''}${r.remarks?' · '+esc(r.remarks):''}${r.followUp?' · 需跟進 '+esc(r.followDate||'未定日期')+' '+esc(r.followNotes||''):''}</div>`}</div>`}
function assignment(id){let c=detail?.find(x=>x.meta.id===id);if(!c||c.teacherEmail!==email(user.email)||current.status!=='active')throw Error('你未獲授權修改呢班，或者行動已結束');return c}
async function draw(id){let c=assignment(id);if(c.selected.length)return;const ref=doc(db,'actions',current.id,'assignments',id);await runTransaction(db,async t=>{let s=await t.get(ref);if(s.data().selected.length)throw Error('本班已抽樣，請重新整理');t.update(ref,{selected:sample(s.data().roster,c.sampleCount).map(x=>x.id),updatedAt:serverTimestamp()})});toast('已抽選學生');await refreshDetail()}
async function replace(id,studentId){let c=assignment(id),roster=c.roster||[],active=new Set(c.selected),previous=new Set((c.replacementLog||[]).map(x=>x.out));let candidate=roster.filter(s=>!active.has(s.id)&&!previous.has(s.id));if(!candidate.length)throw Error('名單內已沒有可重抽學生');const fresh=sample(candidate,1)[0],old=roster.find(s=>s.id===studentId);if(!old)throw Error('找不到學生');if(!confirm(`${old.name} 缺席，改抽 ${fresh.name}？此操作會記錄在案。`))return;const ref=doc(db,'actions',current.id,'assignments',id);await runTransaction(db,async t=>{let s=await t.get(ref),v=s.data();if(!v.selected.includes(studentId)||v.records?.[studentId]?.result)throw Error('名單已更新，或此學生已有檢查紀錄');let excluded=new Set([...v.selected,...(v.replacementLog||[]).map(x=>x.out)]);if(excluded.has(fresh.id))throw Error('名單已更新，請再試');t.update(ref,{selected:v.selected.map(x=>x===studentId?fresh.id:x),replacementLog:[...(v.replacementLog||[]),{out:studentId,outName:old.name,in:fresh.id,inName:fresh.name,at:stamp(),by:email(user.email)}],updatedAt:serverTimestamp()})});await refreshDetail();toast('已記錄缺席並重抽')}
async function save(id,studentId,el){let c=assignment(id);if(!c.selected.includes(studentId))throw Error('學生已不在抽查名單');let result=el.querySelector('input[type=radio]:checked')?.value;if(!result)throw Error('請先揀「沒有問題」或「有問題」');let issues=[...el.querySelectorAll('.issues input:checked')].map(x=>ISSUE_TYPES[Number(x.value)]);if(result==='issue'&&!issues.length)throw Error('請選擇最少一項問題');let followUp=el.querySelector('[data-part=follow]').checked,followDate=el.querySelector('[data-part=followDate]').value,followNotes=el.querySelector('[data-part=followNotes]').value.trim();if(followUp&&(!followDate||!followNotes))throw Error('需要跟進時，請填日期及跟進備註');let record={result,issues:result==='issue'?issues:[],remarks:el.querySelector('[data-part=remarks]').value.trim(),followUp,followDate:followUp?followDate:'',followNotes:followUp?followNotes:'',checkedBy:email(user.email),checkedAt:stamp()};let ref=doc(db,'actions',current.id,'assignments',id);await updateDoc(ref,{[`records.${studentId}`]:record,updatedAt:serverTimestamp()});let records={...(c.records||{}),[studentId]:record},checked=c.selected.filter(x=>records[x]?.result).length;await updateDoc(doc(db,'actions',current.id,'progress',id),{checked,done:checked===c.sampleCount});await refreshDetail();toast('結果已儲存')}
async function toggleStatus(){if(!isLead(current))return;let a=actions.find(x=>x.id===current.id)||current;if(a.status==='active'&&Object.values(a.progress).some(x=>!x.done)&&!confirm('尚有班別未完成。仍然結束行動？'))return;await updateDoc(doc(db,'actions',a.id),{status:a.status==='active'?'completed':'active',updatedAt:serverTimestamp()});toast('行動狀態已更新')}
async function showReport(){if(!isLead(current))throw Error('只有統籌人或管理員可生成整體報告');let snaps=await Promise.all(current.classes.map(c=>getDoc(doc(db,'actions',current.id,'assignments',c.id))));reportAssignments=snaps.map((s,i)=>({meta:current.classes[i],...s.data()}));screen='report';render()}
function renderReport(){const a=actions.find(x=>x.id===current.id)||current;let rows=reportAssignments.flatMap(c=>{let byId=Object.fromEntries((c.roster||[]).map(s=>[s.id,s.name]));return (c.selected||[]).map(id=>({label:c.label,teacher:c.teacherEmail,student:byId[id]||'',r:c.records?.[id]||{}}))});let issueCount=rows.filter(x=>x.r.result==='issue').length,followCount=rows.filter(x=>x.r.followUp).length;shell(`<div class="no-print row between"><button class="btn ghost sm" data-act="back">← 返回行動</button><button class="btn" data-act="print">列印／另存 PDF</button></div><article class="card report"><h1>${esc(a.title)} · 抽查報告</h1><div class="report-meta"><span>日期：${esc(a.date)}</span><span>年級：${esc(a.grade)}</span><span>統籌：${esc(a.coordinatorName)} (${esc(a.coordinatorEmail)})</span><span>班別：${a.classes.length}</span><span>抽查：${rows.length} 人</span><span>有問題：${issueCount} 人</span><span>需跟進：${followCount} 人</span></div><table><thead><tr><th>班別</th><th>學生</th><th>負責老師</th><th>檢查結果／問題</th><th>檢查備註</th><th>跟進日期／備註</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.label)}</td><td>${esc(x.student)}</td><td>${esc(x.teacher)}</td><td>${x.r.result==='ok'?'沒有問題':x.r.result==='issue'?'有問題：'+esc(x.r.issues?.join('、')):'待檢查'}</td><td>${esc(x.r.remarks||'—')}</td><td>${x.r.followUp?esc((x.r.followDate||'')+' '+(x.r.followNotes||'')):'—'}</td></tr>`).join('')}</tbody></table><p class="small">缺席及重抽：${esc(reportAssignments.flatMap(c=>(c.replacementLog||[]).map(x=>`${c.label} ${x.outName} → ${x.inName}（${x.at}）`)).join('；')||'無')}</p><p class="small muted">生成時間：${stamp()} · 如備註較長，列印時可能超過一頁。</p></article>`)}
app.addEventListener('click',async e=>{const b=e.target.closest('[data-act]');if(!b)return;let act=b.dataset.act;b.disabled=true;try{switch(act){case 'login':{let provider=new A.GoogleAuthProvider();try{await A.signInWithPopup(auth,provider)}catch(err){if(['auth/popup-blocked','auth/operation-not-supported-in-this-environment'].includes(err.code))await A.signInWithRedirect(auth,provider);else throw err}break}case 'logout':await A.signOut(auth);screen='home';break;case 'home':screen='home';render();break;case 'history':screen='history';render();break;case 'new':screen='new';render();break;case 'addClass':syncForm();syncDrafts();drafts.push({id:uid(),label:'',teacherEmail:'',roster:''});render();break;case 'removeClass':syncForm();syncDrafts();drafts=drafts.filter(x=>x.id!==b.dataset.id);render();break;case 'open':await openAction(b.dataset.id);break;case 'back':screen='detail';render();break;case 'draw':await draw(b.dataset.class);break;case 'replace':await replace(b.dataset.class,b.dataset.student);break;case 'save':await save(b.dataset.class,b.dataset.student,b.closest('[data-record-class]'));break;case 'report':await showReport();break;case 'print':window.print();break;case 'toggleStatus':await toggleStatus();break}}catch(err){toast(err.message||'操作失敗')}finally{if(b.isConnected)b.disabled=false}});
app.addEventListener('change',e=>{let el=e.target.closest('[data-record-class]');if(!el)return;let r=el.querySelector('input[type=radio]:checked')?.value;el.querySelector('.issues')?.classList.toggle('hidden',r!=='issue');el.querySelector('.follow-fields')?.classList.toggle('hidden',!el.querySelector('[data-part=follow]').checked)});
app.addEventListener('submit',async e=>{if(e.target.id!=='createForm')return;e.preventDefault();const btn=e.target.querySelector('[type=submit]');btn.disabled=true;try{await createAction(e.target)}catch(err){toast(err.message||'建立失敗')}finally{btn.disabled=false}});
